"""One master datasheet for the run: every comparative metric, one row per arm.

    python fast/datasheet.py --src ~/lisa-results

WHY.  The run's numbers live in five files with five schemas -- results_<tag>.json (EVAL12),
visqol_<tag>.json (43 conditions), val_wave_<tag>.json (reproduction), val_wave_decompose_<tag>.json
(the energy-score split) and eight history_<tag>_<arm>.json -- and answering "is arm A better than
arm B" has meant opening three of them and remembering which columns may be compared.  Twice in one
session that produced a wrong comparison: a raw LSD column read against a passthrough one, and a
deterministic arm's only readout read against a sampler's worst readout.

So this emits one document, generated rather than hand-written, with the comparability rule attached
to every column rather than kept in someone's head.  It supersedes the hand-rolled metrics_<tag>.md.

WHAT IT WILL NOT DO IS PUT NON-COMPARABLE NUMBERS SIDE BY SIDE WITHOUT SAYING SO.  Three columns in
this run are routinely misread, and each carries its warning in the table that contains it:

  val_wave   a PROPER SCORE (two-draw energy score; plain L1 for a det arm), not a reconstruction
             error.  A sampler's value is its single-draw L1 minus half its spread, and that spread
             is 63-154% of val_wave.  Both parts are printed next to it.
  LSD        decades of power, not dB (x10 for dB), and the raw and passthrough columns differ.
             Both are printed, labelled.
  SNR        inert: the floor condition, which emits NO high band, outscores six of eight arms.
             Printed with the floor and ceiling rows adjacent so it cannot be read alone.
"""
import argparse
import json
import pathlib
import sys

import numpy as np

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parents[1]))
from fast.run_contract import ARMS, RUN_TAG, STEPS

ORDER = ["det_paper", "det", "es_marg", "es_dec_l0.01", "es_erb_l0.001", "es_erb_l0.01",
         "es_erb_l0.1", "es_dec_erb_l0.1"]


def load(src, tag):
    o = src / "ov3"
    d = {"R": json.loads((o / f"results_{tag}.json").read_text()),
         "V": json.loads((o / f"visqol_{tag}.json").read_text())["agg"],
         "H": {a: json.loads((src / f"history_{tag}_{a}.json").read_text())[a] for a in ARMS}}
    for key, name in (("W", f"val_wave_{tag}.json"), ("D", f"val_wave_decompose_{tag}.json"),
                      ("T", f"latency_{tag}.json")):
        p = o / name
        d[key] = json.loads(p.read_text()) if p.exists() else None
    return d


def fmt(x, n=3, sign=False):
    return "--" if x is None else (f"{x:+.{n}f}" if sign else f"{x:.{n}f}")


def build(d, tag):
    R, V, H, W, D, T = d["R"], d["V"], d["H"], d["W"], d["D"], d["T"]
    g = lambda k: R[k]["eval12"]
    M = R["_M"]
    ideal = 1.0 / (M + 1)
    fl, ce = V["floor: passthrough + empty HB"], V["ceiling: passthrough + true HB"]
    vq_rng = ce["visqol_audio48k"] - fl["visqol_audio48k"]
    share = lambda x: 100 * (x - fl["visqol_audio48k"]) / vq_rng

    def best_lsd(k):
        """Each model at ITS best readout: logmean16+pt for a sampler, its only output for a det arm."""
        r = g(k)
        return (r["readouts_pt"]["logmean16"]["lsd"], "logmean16+pt") if "readouts_pt" in r \
            else (r["single_pt"]["lsd"], "one output")

    def vq(k, readout):
        for name in (f"{k} {readout} | passthrough", f"{k} | passthrough"):
            if name in V:
                return V[name]["visqol_audio48k"]
        return None

    L = []
    A = L.append
    A(f"# {tag} master datasheet")
    A("")
    A(f"Generated by `fast/datasheet.py` from `results_{tag}.json`, `visqol_{tag}.json`, "
      f"`val_wave_{tag}.json`, `val_wave_decompose_{tag}.json` and the eight histories. "
      f"EVAL12: n = {R['_n']} held-out utterances (p236-p238), M = {M} draws. "
      f"Training: {STEPS} steps, batch 64, one shared batch stream, so the arms are paired step for step.")
    A("")
    A("## Read this first")
    A("")
    A("| trap | the rule |")
    A("|---|---|")
    A("| **LSD is not dB** | `lsd_db` omits the factor of 10. Values are decades of power; x10 for dB. "
      "Not comparable with LISA's published LSD, which uses a different transform, axis, epsilon and cap. |")
    A("| **raw vs passthrough** | Every LSD/ViSQOL figure exists both ways. The 16 Sep note reports "
      "passthrough; the EVAL12 table's `LSD` column is raw. Both are labelled here. |")
    A("| **readout** | A sampler has three outputs (one draw, `mean16`, `logmean16`), a deterministic "
      "arm has one. Compare each model at its best readout for the metric in question. |")
    A("| **`val_wave` is a proper score** | Not a reconstruction error. A sampler's value is its "
      "single-draw L1 minus half its spread. Both parts are in section 2. |")
    A("| **SNR is inert** | The floor condition emits no high band at all and outscores six of eight arms. |")
    A("| **CRPS vs a det arm** | A point forecast is a degenerate distribution and must lose a proper "
      "score. `det`/`det_paper` are the reference line on CRPS and `val_wave`, not competitors. |")
    A("")

    # ---- 1. master ----------------------------------------------------------------------------
    A("## 1. Master table -- one row per arm, best readout")
    A("")
    A("| arm | kind | lam | class | LSD pt (best) | readout | deficit 1-draw pt | CRPS | PIT end | "
      "audio ViSQOL | share | corr_err | 1-draw L1 |")
    A("|---|---|---|---|---|---|---|---|---|---|---|---|---|")
    for k in ORDER:
        kind, lam, cls = ARMS[k]
        r = g(k)
        bl, ro = best_lsd(k)
        v = vq(k, "logmean16" if "readouts_pt" in r else None)
        l1 = D[k]["seeds"]["1234"]["l1"] if D else None
        A(f"| `{k}` | {kind} | {lam:g} | {cls} | **{bl:.3f}** | {ro} | "
          f"{r['single_pt']['deficit']:+.2f} | {r['crps']:.4f} | "
          f"{fmt(r.get('pit_end'), 4)} | {fmt(v)} | {fmt(share(v), 1) if v else '--'}% | "
          f"{r['corr_err']:.3f} | {fmt(l1, 6)} |")
    A("")
    A(f"Ideals: LSD 0 | deficit 0 dB | CRPS lower | PIT end {2*ideal:.4f} | "
      f"audio ViSQOL {ce['visqol_audio48k']:.3f} = 100% | corr_err 0 | 1-draw L1 lower.")
    A("")

    # ---- 2. training record -------------------------------------------------------------------
    A("## 2. Training record, at step 104950/104950")
    A("")
    A("| arm | val_wave (proper score) | val spread | 1-draw L1 (error) | val_spec | own objective |")
    A("|---|---|---|---|---|---|")
    for k in ORDER:
        h = H[k]
        s = D[k]["seeds"]["1234"] if D else None
        A(f"| `{k}` | {h['val_wave'][-1]:.6f} | {fmt(s['spread'] if s else None, 6)} | "
          f"{fmt(s['l1'] if s else None, 6)} | {h['val_spec'][-1]:.4f} | {h['val_loss'][-1]:.6f} |")
    A("")
    A("`val_wave` and `1-draw L1` rank the arms in **opposite order**: the energy score credits a "
      "sampler for spread, which a deterministic arm structurally cannot have. `own objective` is "
      "eight different functions and is never a leaderboard -- comparable only within a shared "
      "`(kind, lambda)` pair, i.e. `{es_marg, es_dec_l0.01}` and `{es_erb_l0.1, es_dec_erb_l0.1}`. "
      "`det_paper`'s `val_spec` is AMP rounding noise counted as signal (fp32 gives 1.944, not 1.603).")
    A("")

    # ---- 3. EVAL12 fidelity -------------------------------------------------------------------
    A("## 3. EVAL12 -- fidelity and spectrum")
    A("")
    A("| arm | SNR | LSD raw | LSD pt | HB-LSD | deficit 1-draw raw | deficit mean16 | HB kappa | HB coherent |")
    A("|---|---|---|---|---|---|---|---|---|")
    for k in ORDER:
        r, s = g(k), g(k)["single"]
        A(f"| `{k}` | {s['snr']:.2f} | {s['lsd']:.3f} | {r['single_pt']['lsd']:.3f} | {s['hb_lsd']:.3f} | "
          f"{s['deficit']:+.2f} | {fmt(r['mean']['deficit'] if 'mean' in r else None, 2, True)} | "
          f"{s['hb_kappa']:+.3f} | {s['hb_coh']:.4f} |")
    for nm, key in (("floor: pt + empty HB", "_floor"), ("ceiling: pt + true HB", "_ceiling")):
        a = R[key]
        A(f"| *{nm}* | {a['snr']:.2f} | {a['lsd']:.3f} | -- | {a['hb_lsd']:.3f} | {a['deficit']:+.2f} | -- | -- | -- |")
    A("")
    A("`HB coherent` is the predictable fraction of the high band: 0.005-0.012 for every arm, i.e. "
      "the band is essentially incoherent with the truth and no model has waveform-domain skill in it. "
      "That is why SNR cannot separate the arms and why calibration, not accuracy, is the live axis.")
    A("")

    # ---- 4. calibration -----------------------------------------------------------------------
    A("## 4. EVAL12 -- probabilistic and calibration (samplers only)")
    A("")
    A(f"| arm | CRPS | sliced CRPS | PIT end | /ideal | PIT bin0 /ideal | PIT binM /ideal | "
      f"SNR gap | of calibrated {g('es_marg')['snr_gap_calibrated']:.2f} dB |")
    A("|---|---|---|---|---|---|---|---|---|")
    for k in ORDER:
        r = g(k)
        if "pit_hist" not in r:
            A(f"| `{k}` | {r['crps']:.4f} | {r['sliced_crps']:.4f} | *deterministic: CRPS = MAE, no PIT* | | | | | |")
            continue
        h = np.array(r["pit_hist"], float); h /= h.sum()
        A(f"| `{k}` | {r['crps']:.4f} | {r['sliced_crps']:.4f} | {r['pit_end']:.4f} | "
          f"{r['pit_end']/(2*ideal):.2f}x | {h[0]/ideal:.2f}x | **{h[-1]/ideal:.2f}x** | "
          f"{r['snr_gap']:.2f} | {100*r['snr_gap']/r['snr_gap_calibrated']:.0f}% |")
    A("")
    A(f"PIT end ideal {2*ideal:.4f}; per-bin ideal {ideal:.4f}. **The bottom bin is at its ideal value "
      "for every arm and all the excess is in the top bin** -- a one-sided energy bias, not a narrow "
      "ensemble. Ranks are per time-frequency bin and heavily correlated, so binomial error bars on "
      "them are far too tight. The SNR gap says every arm carries a quarter to a third of the spread a "
      "calibrated ensemble would have.")
    A("")

    # ---- 5. readouts --------------------------------------------------------------------------
    # Four readouts exist, not three: logmean4 is in results_<tag>.json and is a real intermediate
    # point on the energy/distortion curve, not a curiosity.  ViSQOL scored only three of them
    # (e5_visqol.py's conditions_for omits logmean4), so that column is blank for it -- blank
    # because it was never computed, which is a different statement from a dash meaning "n/a".
    RO = [("one draw", "single", "tau=1"), ("logmean4", "logmean4", None),
          ("logmean16", "logmean16", "logmean16"), ("mean16", "mean", "mean16")]

    def ro_block(k, key, pt):
        """The metric dict for one (arm, readout, raw|pt), or None if that readout does not exist."""
        r = g(k)
        suf = "_pt" if pt else ""
        if key in ("single", "mean"):
            return r.get(key + suf)
        return r.get("readouts" + suf, {}).get(key)

    def ro_vq(k, vname, pt):
        if vname is None:
            return None
        base = f"{k} {vname}" if vname else k
        return V.get(base + (" | passthrough" if pt else ""), {}).get("visqol_audio48k")

    A("## 5. Every readout")
    A("")
    A("A sampler has **four** readouts and a deterministic arm has one. `raw` is the model's own "
      "output; `pt` passes the given baseband through, which is how it would ship.")
    A("")
    A("| arm | readout | SNR | LSD raw | LSD pt | HB-LSD pt | deficit raw | deficit pt | HB kappa | "
      "audio ViSQOL raw | audio ViSQOL pt |")
    A("|---|---|---|---|---|---|---|---|---|---|---|")
    for k in ORDER:
        r = g(k)
        rows = [("one output", "single", None)] if "readouts_pt" not in r else RO
        for label, key, vname in rows:
            raw, pt = ro_block(k, key, False), ro_block(k, key, True)
            if pt is None:
                continue
            vr, vp = ro_vq(k, vname if vname is not None else "", False), ro_vq(k, vname if vname is not None else "", True)
            if label == "one output":
                vr, vp = V.get(k, {}).get("visqol_audio48k"), V.get(f"{k} | passthrough", {}).get("visqol_audio48k")
            A(f"| `{k}` | {label} | {pt['snr']:.2f} | {fmt(raw['lsd'] if raw else None)} | {pt['lsd']:.3f} | "
              f"{pt['hb_lsd']:.3f} | {fmt(raw['deficit'] if raw else None, 2, True)} | {pt['deficit']:+.2f} | "
              f"{pt['hb_kappa']:+.3f} | {fmt(vr)} | {fmt(vp)} |")
    A("")
    A("`logmean4` was never scored by ViSQOL -- `e5_visqol.py`'s `conditions_for` builds one draw, "
      "`mean16` and `logmean16` only -- so those two cells are blank because the number does not "
      "exist, not because it does not apply.")
    A("")

    A("### 5b. The same thing pivoted, passthrough only -- for comparing across readouts")
    A("")
    for metric, label, nd, sign, ideal in (("lsd", "LSD", 3, False, "0"),
                                           ("deficit", "deficit dB", 2, True, "0 dB"),
                                           ("snr", "SNR dB", 2, False, "inert; see section 3")):
        A(f"**{label}** (ideal {ideal})")
        A("")
        A("| arm | one draw | logmean4 | logmean16 | mean16 | best |")
        A("|---|---|---|---|---|---|")
        for k in ORDER:
            r = g(k)
            if "readouts_pt" not in r:
                v = r["single_pt"][metric]
                A(f"| `{k}` | {fmt(v, nd, sign)} | *no ensemble* | | | {fmt(v, nd, sign)} |")
                continue
            vals = {lb: ro_block(k, key, True)[metric] for lb, key, _ in RO}
            pick = (max if (metric == "deficit" or metric == "snr") else min)(vals, key=lambda lb: vals[lb])
            cells = " | ".join(f"**{fmt(vals[lb], nd, sign)}**" if lb == pick else fmt(vals[lb], nd, sign)
                               for lb, _, _ in RO)
            A(f"| `{k}` | {cells} | {pick} |")
        A("")
    A("**audio ViSQOL** (floor {:.3f}, ceiling {:.3f}; `logmean4` not scored)".format(
        fl["visqol_audio48k"], ce["visqol_audio48k"]))
    A("")
    A("| arm | one draw | logmean16 | mean16 | best |")
    A("|---|---|---|---|---|")
    for k in ORDER:
        r = g(k)
        if "readouts_pt" not in r:
            v = V.get(f"{k} | passthrough", {}).get("visqol_audio48k")
            A(f"| `{k}` | {fmt(v)} | *no ensemble* | | {fmt(v)} |")
            continue
        vals = {lb: ro_vq(k, vn, True) for lb, _, vn in RO if vn}
        pick = max(vals, key=lambda lb: vals[lb] if vals[lb] is not None else -9)
        cells = " | ".join(f"**{fmt(vals[lb])}**" if lb == pick else fmt(vals[lb]) for lb in ("one draw", "logmean16", "mean16"))
        A(f"| `{k}` | {cells} | {pick} |")
    A("")
    A("**The readouts trace an energy/distortion curve and averaging moves along it monotonically.** "
      "More draws averaged means less high-band energy (deficit falls) and a better estimate of the "
      "log-magnitude conditional mean (LSD falls, then LSD's own optimum is reached). One draw holds "
      "the energy; `logmean16` holds the spectrum; `logmean4` sits between and is the best single "
      "compromise if energy matters as much as distortion. `mean16` -- averaging the WAVEFORMS rather "
      "than the log-magnitudes -- is dominated on both LSD and deficit by `logmean16` while winning "
      "SNR and PESQ, which is the clearest statement in the run that those two judges are measuring "
      "the wrong thing. A deterministic arm occupies ONE point on this curve and cannot move along it.")
    A("")

    # ---- 6. perceptual ------------------------------------------------------------------------
    A("## 6. Perceptual -- each judge's whole range for this task")
    A("")
    A("| judge | floor | ceiling | range | `naive` (no high band) sits at |")
    A("|---|---|---|---|---|")
    for key, nm in (("visqol_audio48k", "**ViSQOL audio48k**"), ("visqol_speech16k", "ViSQOL speech16k"),
                    ("pesq_wb", "PESQ wb"), ("nsim_audio48k", "NSIM audio"), ("nsim_speech16k", "NSIM speech")):
        rng = ce[key] - fl[key]
        A(f"| {nm} | {fl[key]:.3f} | {ce[key]:.3f} | **{rng:.3f}** | "
          f"{100*(V['naive'][key]-fl[key])/rng:.1f}% |")
    A("")
    A("Lead with **audio48k**: 32 ERB bands to 24 kHz, so it sees the whole invented band, and `naive` "
      "correctly sits at 0.3% of it. Speech mode resamples to 16 kHz and sees ~11% of the problem; "
      "passthrough alone, which touches only the baseband, moves it by 82% of its range. PESQ puts "
      "`naive` 28% of the way to perfect and ranks `det_paper` 2nd of 43 conditions. Both should be "
      "retired for 12 -> 48 kHz; NSIM is the mapping-free score and MOS-LQO saturates below 5.")
    A("")

    # ---- 7. verification ----------------------------------------------------------------------
    if W:
        A("## 7. Checkpoint verification")
        A("")
        A("| arm | val_wave recorded | reproduced | AMP term | residual | val_spec recorded | reproduced | AMP term | residual |")
        A("|---|---|---|---|---|---|---|---|---|")
        for k in ORDER:
            w, s = W[k]["val_wave"], W[k]["val_spec"]
            A(f"| `{k}` | {w['recorded']:.6f} | {w['pred']:.6f} | {100*w['d_amp']/w['mu']:+.2f}% | "
              f"{100*w['resid']/w['recorded']:+.3f}% | {s['recorded']:.4f} | {s['pred']:.4f} | "
              f"{100*s['d_amp']/s['mu']:+.2f}% | {100*s['resid']/s['recorded']:+.3f}% |")
        A("")
        A("Identity passes by 13-1800 bands: every arm's own recorded curve is its nearest match among "
          "the arms it could be confused with. Reproduced = mean(fp32 over 4 eps seeds) + (bf16 - fp32). "
          "All eight `val_wave` residuals are negative (sign test p = 0.0078) at 0.1-0.3%: the CPU-bf16 "
          "stand-in for A100 bf16, not the checkpoints.")
        A("")

    # ---- 8. latency ---------------------------------------------------------------------------
    if T:
        lat, inf, mc = T["latency"], T["info"], T["macs"]
        uk, udur = T["utt"]["key"], T["utt"]["seconds"]
        ms = lambda k, key: lat[k][key]["median_ms"] if key in lat[k] else None
        A("## 8. Latency")
        A("")
        A(f"Measured by `fast/bench_latency.py` on {T['machine'].get('cpu', T['machine']['machine'])}, "
          f"{T['threads']} threads, torch {T['torch']}, fp32 eager, batch 1; median of repeated runs. "
          f"One pass = 12 kHz input on the device to 48 kHz output on the host, `reconstruct()`'s path. "
          f"Shipped = the eval's own pipeline on `{T['utt']['name']}` ({udur:.2f} s) with baseband passthrough. "
          f"RTF = compute time / audio time.")
        A("")
        A(f"| arm | class | params | 20 ms frame | 1 s | {udur:.2f} s utterance | RTF | shipped one output or draw + pt | shipped logmean16 + pt | RTF |")
        A("|---|---|---|---|---|---|---|---|---|---|")
        for k in ORDER:
            if k not in lat:
                continue
            one, lm = ms(k, "cpu/shipped_one_pt"), ms(k, "cpu/shipped_logmean16_pt")
            lm_ms = "--" if lm is None else "%.0f ms" % lm
            lm_rtf = "--" if lm is None else "%.2f" % lat[k]["cpu/shipped_logmean16_pt"]["rtf"]
            A(f"| `{k}` | {inf[k]['cls']} | {inf[k]['params']:,} | {ms(k, 'cpu/20ms'):.2f} ms | "
              f"{ms(k, 'cpu/1s'):.1f} ms | {ms(k, f'cpu/{uk}'):.1f} ms | {lat[k][f'cpu/{uk}']['rtf']:.3f} | "
              f"{one:.0f} ms | {lm_ms} | {lm_rtf} |")
        A("")
        base = mc["enc"] + mc["dec1"] + mc["dec_rest"]
        sd = [k for k in ORDER if k in lat and inf[k]["cls"] == "LISASD"]
        s1 = [k for k in ORDER if k in lat and inf[k]["cls"] == "LISAS"]
        over = 100 * (np.mean([ms(k, "cpu/1s") for k in sd]) / np.mean([ms(k, "cpu/1s") for k in s1]) - 1) if sd and s1 else None
        pt_share = 100 * T["passthrough_ms"] / np.mean([ms(k, "cpu/shipped_one_pt") for k in ORDER if k in lat])
        A(f"- **Kind and lambda do not touch inference cost.** The architecture is {base / 1e9:.2f} GMAC per audio second, "
          f"{100 * mc['dec_rest'] / base:.0f}% of it decoder layers 2-5 at 48 kHz, and every arm runs one pass at "
          f"about {100 * np.median([lat[k][f'cpu/{uk}']['rtf'] for k in lat]):.1f}% of real time.")
        if over is not None:
            A(f"- **Decoder noise costs {over:.0f}% of wall time for {100 * mc['dec_noise'] / base:.0f}% of the MACs.** LISASD draws "
              f"{T['fs_lo'] * 4 * 4 // 1000}k Gaussians per audio second at the output rate and multiplies them in at the decoder's first layer.")
        ro = [lat[k]["cpu/shipped_logmean16_pt"]["rtf"] for k in sd + s1 if "cpu/shipped_logmean16_pt" in lat[k]]
        if ro:
            A(f"- **The 16-draw readouts are 16 passes plus an STFT**, {min(ro):.2f}-{max(ro):.2f} RTF, "
              f"and whole-utterance as implemented.")
        A(f"- **Passthrough is {pt_share:.0f}% of the shipped one-pass time** ({T['passthrough_ms']:.0f} ms: scipy resample_poly plus two "
          f"whole-utterance FFT brick-wall splits), not the model. A deployed pipeline would use a short filter.")
        A(f"- **Algorithmic lookahead is {1e3 * T['lookahead_samples_12k'] / T['fs_lo']:.1f} ms**: {T['lookahead_samples_12k']} input samples "
          f"(encoder receptive field plus the decoder's right-hand neighbour). One-draw output can stream; passthrough and logmean16 cannot as written.")
        if "mps" in T["devices"]:
            fu = [ms(k, f"mps/{uk}") for k in lat]
            fr = [ms(k, "mps/20ms") for k in lat]
            cu = [ms(k, f"cpu/{uk}") for k in lat]
            cr = [ms(k, "cpu/20ms") for k in lat]
            # Both ratios are measured, not assumed: the crossover moves with thermal state and torch version.
            long_x, short_x = np.median(fu) / np.median(cu), np.median(fr) / np.median(cr)
            verdict = ("MPS wins only at length" if long_x < 0.95 < short_x else
                       "MPS loses at both lengths" if long_x > 1.05 else
                       "MPS wins at both lengths" if short_x < 0.95 else "MPS and CPU are within noise")
            A(f"- **{verdict}.** Whole utterance {min(fu):.0f}-{max(fu):.0f} ms against {min(cu):.0f}-{max(cu):.0f} ms "
              f"on CPU ({long_x:.2f}x); 20 ms frame {min(fr):.2f}-{max(fr):.2f} ms against {min(cr):.2f}-{max(cr):.2f} ms "
              f"({short_x:.2f}x), where the small kernels are dispatch-bound. Run-to-run scatter on the short frame is "
              f"large, so treat the frame ratio as an order of magnitude, not a figure.")
        A("")

    A("## 9. Provenance")
    A("")
    A(f"- `fast/convert_ckpt.py` -- train_arm checkpoints to the blob `load_arm` reads; 4 checks x 8 arms")
    A(f"- `fast/vctk_local.py` -- EVAL12 by partial read (~230 MB, not 11.7 GB)")
    A(f"- `fast/run_e4_eval.py` -> `results_{tag}.json`, `table_{tag}.md`")
    A(f"- `fast/run_e5_visqol.py` -> `visqol_{tag}.json` ({len(V)} conditions, lattice mapping)")
    A(f"- `fast/val_wave_check.py` -> `val_wave_{tag}.json`")
    A(f"- `fast/val_wave_decompose.py` -> `val_wave_decompose_{tag}.json`")
    A(f"- `fast/bench_latency.py` -> `latency_{tag}.json` (this machine, fp32 eager)")
    A(f"- `fast/plot_histories.py`, `fast/compare.py`, `fast/publish_results.py`")
    A("")
    A("Full definitions, traps and provenance for every metric: `notes/metrics-reference.md`. "
      "Findings and interpretation: `notes/2026-09-21-eval-results.md`.")
    return "\n".join(L)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--src", default="~/lisa-results")
    ap.add_argument("--tag", default=RUN_TAG)
    ap.add_argument("--out", default=None)
    a = ap.parse_args()
    src = pathlib.Path(a.src).expanduser().resolve()
    txt = build(load(src, a.tag), a.tag)
    out = pathlib.Path(a.out).expanduser() if a.out else src / "ov3" / f"DATASHEET_{a.tag}.md"
    out.write_text(txt + "\n")
    print(txt)
    print(f"\n-> {out}  ({len(txt)/1024:.1f} KB)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
